const data={
 servicer:{label:'SERVICER COMMAND CENTER',greeting:'Good morning, Mike.',copy:'Protect your reputation, reward reliable customers, and resolve complaints with verified evidence.',action:'Share review QR',secondary:'Create verified complaint',standing:'Business Verified',metricLabel:'Preferred members',metricValue:'1,284',rewardLabel:'Rewards issued',rewardValue:'42,860',benefitTitle:'Active customer benefits'},
 customer:{label:'CUSTOMER STANDING & BENEFITS',greeting:'Your reputation is working for you.',copy:'Review your verified history, respond to disputes, unlock benefits, and control your data permissions.',action:'Share my customer QR',secondary:'View my RMC Report',standing:'Preferred',metricLabel:'Benefits unlocked',metricValue:'12',rewardLabel:'Test rewards earned',rewardValue:'286.5',benefitTitle:'Your unlocked benefits'}
};
const cases=[['RMC-2048','Evidence screening · No rating effect','2 hours ago'],['RMC-2039','Customer response received','Yesterday'],['RMC-2018','Resolved · Standing restored','Aug 11']];
const benefits=[['Priority reservation','Preferred tier','Active at 4 locations'],['15% service discount','Premier tier','Unlocked'],['Complimentary upgrade','Premier tier','Available now'],['Flexible cancellation','Verified tier','Active']];
const tiers=[['Verified','Identity + verified transaction',['Early access offers','Recognition badge','DISC, VISC, or AMDX rewards']],['Preferred','Strong verified reliability',['Priority reservations','Preferred pricing','Flexible scheduling']],['Premier','Exceptional verified history',['VIP access','Complimentary upgrades','Premium support']]];
const tags=[['Service category','General type of service purchased',2.5],['Transaction timing','Month and time window; no exact timestamp',3],['Resolution outcome','Whether a dispute was resolved',5],['Aggregated satisfaction','Anonymous service-quality signals',3.5],['AI training license','De-identified metadata for approved models',4.5]];
function rows(items){return items.map(x=>`<div class="row"><div><strong>${x[0]}</strong><small>${x[1]}</small></div><span class="value">${x[2]}</span></div>`).join('')}
document.querySelector('#case-list').innerHTML=rows(cases);document.querySelector('#benefit-list').innerHTML=rows(benefits);
document.querySelector('#tier-grid').innerHTML=tiers.map(t=>`<article class="tier"><span class="level">${t[1]}</span><h3>${t[0]}</h3><ul>${t[2].map(v=>`<li>${v}</li>`).join('')}</ul><button class="text-button">Configure tier →</button></article>`).join('');
document.querySelector('#tag-list').innerHTML=tags.map((t,i)=>`<label class="tag"><input type="checkbox" data-amount="${t[2]}" ${i<3?'checked':''}><span><strong>${t[0]}</strong><small>${t[1]}</small></span><span class="amount">+${t[2]}</span></label>`).join('');
let activeView='servicer';function switchView(view){activeView=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const d=data[view];['label','greeting','copy'].forEach(k=>document.querySelector(`#${k==='label'?'view-label':k==='copy'?'hero-copy':k}`).textContent=d[k]);document.querySelector('#primary-action').textContent=d.action;document.querySelector('#secondary-action').textContent=d.secondary;document.querySelector('#standing').textContent=d.standing;document.querySelector('#metric-label').textContent=d.metricLabel;document.querySelector('#metric-value').textContent=d.metricValue;document.querySelector('#reward-label').textContent=d.rewardLabel;document.querySelector('#reward-value').textContent=d.rewardValue;document.querySelector('#benefit-title').textContent=d.benefitTitle}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function openPanel(id){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===id))}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPanel(b.dataset.open));
const modal=document.querySelector('#modal'),qrModal=document.querySelector('#qr-modal');document.querySelector('#secondary-action').onclick=()=>activeView==='servicer'?modal.showModal():openPanel('overview');document.querySelector('#primary-action').onclick=()=>{const customer=activeView==='customer';document.querySelector('#qr-eyebrow').textContent=customer?'CUSTOMER REVIEW REQUEST':'SERVICER REVIEW REQUEST';document.querySelector('#qr-title').textContent=customer?'Help build my verified customer standing':'Share an honest experience';document.querySelector('#qr-copy').textContent=customer?'Scan to review this verified customer, passenger, or guest interaction. Verified participation may earn points toward benefits; the rating itself does not change the points.':'Scan to review this verified service interaction on Google. The request is for honest feedback—positive or negative.';document.querySelector('#qr-code').textContent=customer?'RMC-C-7394':'RMC-S-4821';document.querySelector('#points-copy').innerHTML=customer?'<strong>+25 participation points</strong><span>A verified review submission earns points regardless of sentiment.</span>':'<strong>Transparent request</strong><span>No benefit depends on leaving a positive review.</span>';drawQR(customer?7394:4821);qrModal.showModal()};
function drawQR(seed){const c=document.querySelector('#qr-canvas'),x=c.getContext('2d'),n=29,s=c.width/n;x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const finder=(r,k)=>{x.fillStyle='#0b2545';x.fillRect(k*s,r*s,7*s,7*s);x.fillStyle='#fff';x.fillRect((k+1)*s,(r+1)*s,5*s,5*s);x.fillStyle='#0b2545';x.fillRect((k+2)*s,(r+2)*s,3*s,3*s)};finder(1,1);finder(1,21);finder(21,1);let v=seed;for(let r=0;r<n;r++)for(let k=0;k<n;k++){v=(v*9301+49297)%233280;if(v/233280>.53&&!((r<9&&k<9)||(r<9&&k>19)||(r>19&&k<9))){x.fillStyle=(r+k)%7===0?'#00a88f':'#0b2545';x.fillRect(k*s,r*s,Math.ceil(s),Math.ceil(s))}}}
drawQR(4821);document.querySelector('#copy-link').onclick=()=>{document.querySelector('#copy-link').textContent='Copied'};
function total(){const n=[...document.querySelectorAll('.tag input:checked')].reduce((s,x)=>s+Number(x.dataset.amount),0);document.querySelector('#reward-total').textContent=n.toFixed(1)}document.querySelectorAll('.tag input').forEach(x=>x.onchange=total);total();
document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-token]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#reward-token').textContent=b.dataset.token});
document.querySelector('#approve-tags').onclick=()=>{const b=document.querySelector('#approve-tags');b.textContent='Consent recorded · Test rewards pending';b.disabled=true};
