const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const PUBLIC=path.join(__dirname,'public');const SECRET=process.env.RMC_SIGNING_SECRET||'local-prototype-secret-change-before-deployment';
const db={accounts:new Map(),interactions:new Map(),invitations:new Map(),complaints:new Map(),benefits:new Map(),consents:new Map(),rewards:new Map(),reviews:new Map(),redemptions:new Map(),audit:new Map()};const rateBuckets=new Map();
const seed=()=>{if(db.accounts.size)return;db.accounts.set('acct-c-100',{id:'acct-c-100',role:'customer',displayName:'Jordan Customer',standing:'Preferred',score:782,points:425});db.accounts.set('acct-s-200',{id:'acct-s-200',role:'servicer',displayName:'Harbor House',verified:true});db.benefits.set('benefit-1',{id:'benefit-1',servicerId:'acct-s-200',name:'Priority reservation',tier:'Preferred',active:true});db.benefits.set('benefit-2',{id:'benefit-2',servicerId:'acct-s-200',name:'15% service discount',tier:'Premier',active:true})};seed();
const id=p=>`${p}_${crypto.randomUUID()}`;const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>1e6)reject(Error('body_too_large'))});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(Error('invalid_json'))}})});
const sign=value=>crypto.createHmac('sha256',SECRET).update(value).digest('base64url');
const persist=()=>{const file=process.env.RMC_DATA_FILE;if(!file)return;const snapshot={};for(const [name,value] of Object.entries(db))snapshot[name]=[...value.values()];fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(snapshot,null,2))};
const restore=()=>{const file=process.env.RMC_DATA_FILE;if(!file||!fs.existsSync(file))return;const snapshot=JSON.parse(fs.readFileSync(file,'utf8'));for(const [name,records] of Object.entries(snapshot)){if(!db[name]||!Array.isArray(records))continue;for(const record of records)db[name].set(record.id,record)}};
const verifyToken=token=>{const [encoded,signature]=String(token||'').split('.');if(!encoded||!signature)return null;let payload;try{payload=Buffer.from(encoded,'base64url').toString()}catch{return null}if(signature.length!==sign(payload).length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(sign(payload))))return null;const [interactionId,direction,expiresAt]=payload.split('.');if(Date.now()>Number(expiresAt))return null;return{interactionId,direction,expiresAt:Number(expiresAt)}};
const sessionToken=(accountId,expiresAt=Date.now()+8*60*60*1000)=>{const payload=`session.${accountId}.${expiresAt}`,encoded=Buffer.from(payload).toString('base64url');return`${encoded}.${sign(payload)}`};
const authenticate=req=>{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const [encoded,signature]=token.split('.');if(!encoded||!signature)return null;let payload;try{payload=Buffer.from(encoded,'base64url').toString()}catch{return null}if(signature.length!==sign(payload).length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(sign(payload))))return null;const [kind,accountId,expiresAt]=payload.split('.');if(kind!=='session'||Date.now()>Number(expiresAt))return null;return db.accounts.get(accountId)||null};
const audit=(action,actorId,targetId,details={})=>{const record={id:id('audit'),action,actorId:actorId||'system',targetId:targetId||null,details,createdAt:new Date().toISOString()};db.audit.set(record.id,record);return record};
const requireActor=(req,res,roles=[])=>{if(process.env.RMC_REQUIRE_AUTH!=='1')return{account:authenticate(req),bypass:true};const account=authenticate(req);if(!account){json(res,401,{error:'authentication_required'});return null}if(roles.length&&!roles.includes(account.role)){json(res,403,{error:'role_not_authorized'});return null}return{account,bypass:false}};
const allowRequest=req=>{const limit=Number(process.env.RMC_RATE_LIMIT||120),windowMs=60_000,key=req.socket.remoteAddress||'local',now=Date.now(),entry=rateBuckets.get(key);if(!entry||now-entry.startedAt>=windowMs){rateBuckets.set(key,{startedAt:now,count:1});return true}entry.count+=1;return entry.count<=limit};
const staticFile=(req,res)=>{const route=req.url==='/'?'/index.html':req.url;const safe=path.normalize(route).replace(/^([.][.][/\\])+/, '');const file=path.join(PUBLIC,safe);if(!file.startsWith(PUBLIC)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return false;const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);return true};
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{status:'ok',mode:'prototype',rewards:'test-only'});
 if(req.method==='POST'&&url.pathname==='/api/sessions'){const b=await body(req),account=db.accounts.get(b.accountId);if(!account||b.prototypeCode!=='RMC-DEMO')return json(res,401,{error:'invalid_prototype_credentials'});const token=sessionToken(account.id);audit('session.created',account.id,account.id);return json(res,201,{token,account:{id:account.id,role:account.role,displayName:account.displayName},expiresInSeconds:28800,prototype:true})}
 if(req.method==='GET'&&url.pathname==='/api/audit'){const actor=requireActor(req,res,['servicer','admin']);if(!actor)return;return json(res,200,{items:[...db.audit.values()].slice(-100)})}
 const accountMatch=url.pathname.match(/^\/api\/accounts\/([^/]+)\/summary$/);if(req.method==='GET'&&accountMatch){const account=db.accounts.get(accountMatch[1]);if(!account)return json(res,404,{error:'account_not_found'});const interactions=[...db.interactions.values()].filter(x=>x.customerId===account.id||x.servicerId===account.id),interactionIds=new Set(interactions.map(x=>x.id));return json(res,200,{account,interactions,reviews:[...db.reviews.values()].filter(x=>x.subjectId===account.id||x.authorId===account.id),complaints:[...db.complaints.values()].filter(x=>interactionIds.has(x.interactionId)),benefits:[...db.benefits.values()],redemptions:[...db.redemptions.values()].filter(x=>x.accountId===account.id),consents:[...db.consents.values()].filter(x=>x.accountId===account.id),rewards:[...db.rewards.values()].filter(x=>x.accountId===account.id)})}
 if(req.method==='GET'&&url.pathname==='/api/dashboard'){const role=url.searchParams.get('role')||'customer';return json(res,200,{role,standing:role==='customer'?{level:'Preferred',score:782,pendingExcluded:1}:{level:'Business Verified'},benefits:[...db.benefits.values()],openVerifications:1,rewardAssets:['DISC','VISC','AMDX']})}
 if(req.method==='POST'&&url.pathname==='/api/interactions'){const actor=requireActor(req,res,['servicer']);if(!actor)return;const b=await body(req);if(!db.accounts.has(b.customerId)||!db.accounts.has(b.servicerId))return json(res,422,{error:'verified_accounts_required'});const record={id:id('int'),customerId:b.customerId,servicerId:b.servicerId,occurredAt:b.occurredAt||new Date().toISOString(),category:b.category||'service',status:'verified',createdAt:new Date().toISOString()};db.interactions.set(record.id,record);audit('interaction.created',actor.account?.id,record.id,{customerId:b.customerId,servicerId:b.servicerId});persist();return json(res,201,record)}
 if(req.method==='POST'&&url.pathname==='/api/qr-invitations'){const b=await body(req),interaction=db.interactions.get(b.interactionId);if(!interaction)return json(res,404,{error:'verified_interaction_not_found'});if(!['servicer_to_customer','customer_to_servicer'].includes(b.direction))return json(res,422,{error:'invalid_direction'});const expiresAt=Date.now()+15*60*1000,payload=`${interaction.id}.${b.direction}.${expiresAt}`,token=`${Buffer.from(payload).toString('base64url')}.${sign(payload)}`;const record={id:id('qr'),interactionId:interaction.id,direction:b.direction,expiresAt:new Date(expiresAt).toISOString(),singleUse:true,status:'active',token};db.invitations.set(record.id,record);persist();return json(res,201,record)}
 if(req.method==='POST'&&url.pathname==='/api/qr-invitations/redeem'){const b=await body(req),verified=verifyToken(b.token),invitation=[...db.invitations.values()].find(x=>x.token===b.token);if(!verified||!invitation)return json(res,401,{error:'invalid_or_expired_invitation'});if(invitation.status!=='active')return json(res,409,{error:'invitation_already_used'});if(invitation.direction==='servicer_to_customer'){invitation.status='used';invitation.usedAt=new Date().toISOString();persist();return json(res,200,{direction:invitation.direction,destination:'google_review',participationPoints:0,disclosure:'Honest feedback is requested; no reward depends on sentiment.'})}const interaction=db.interactions.get(invitation.interactionId),customer=db.accounts.get(interaction.customerId);const review={id:id('review'),interactionId:interaction.id,subjectId:customer.id,authorId:interaction.servicerId,rating:Number(b.rating||0),narrative:String(b.narrative||''),status:'submitted_for_verification',createdAt:new Date().toISOString()};db.reviews.set(review.id,review);customer.points=(customer.points||0)+25;invitation.status='used';invitation.usedAt=new Date().toISOString();persist();return json(res,201,{review,participationPoints:25,pointsBalance:customer.points,disclosure:'Points reward verified participation and do not depend on rating or sentiment.'})}
 if(req.method==='POST'&&url.pathname==='/api/complaints'){const actor=requireActor(req,res,['servicer']);if(!actor)return;const b=await body(req);if(!db.interactions.has(b.interactionId))return json(res,422,{error:'verified_interaction_required'});if(!b.summary||!b.category)return json(res,422,{error:'category_and_factual_summary_required'});const record={id:id('case'),interactionId:b.interactionId,category:b.category,summary:b.summary,evidence:b.evidence||[],status:'submitted',ratingEffect:false,customerResponseStatus:'notified',createdAt:new Date().toISOString()};db.complaints.set(record.id,record);audit('complaint.submitted',actor.account?.id,record.id,{ratingEffect:false});persist();return json(res,201,record)}
 const caseMatch=url.pathname.match(/^\/api\/complaints\/([^/]+)\/transition$/);if(req.method==='POST'&&caseMatch){const record=db.complaints.get(caseMatch[1]);if(!record)return json(res,404,{error:'case_not_found'});const b=await body(req),allowed={submitted:['transaction_verified','rejected'],transaction_verified:['evidence_screening','rejected'],evidence_screening:['customer_response','rejected'],customer_response:['human_review','resolved'],human_review:['verified_unresolved','resolved','rejected']};if(!(allowed[record.status]||[]).includes(b.status))return json(res,409,{error:'invalid_case_transition',from:record.status});record.status=b.status;record.ratingEffect=b.status==='verified_unresolved'&&b.humanDecision===true;return json(res,200,record)}
 if(req.method==='GET'&&url.pathname==='/api/benefits')return json(res,200,{items:[...db.benefits.values()]});
 const benefitMatch=url.pathname.match(/^\/api\/benefits\/([^/]+)\/redeem$/);if(req.method==='POST'&&benefitMatch){const b=await body(req),benefit=db.benefits.get(benefitMatch[1]),account=db.accounts.get(b.accountId);if(!benefit||!account)return json(res,404,{error:'benefit_or_account_not_found'});if(account.role!=='customer'||!['Preferred','Premier'].includes(account.standing))return json(res,403,{error:'standing_not_eligible'});const record={id:id('redeem'),benefitId:benefit.id,accountId:account.id,status:'issued',code:crypto.randomBytes(5).toString('hex').toUpperCase(),createdAt:new Date().toISOString()};db.redemptions.set(record.id,record);persist();return json(res,201,record)}
 if(req.method==='POST'&&url.pathname==='/api/consents'){const b=await body(req);if(!db.accounts.has(b.accountId))return json(res,404,{error:'account_not_found'});if(!Array.isArray(b.metadataTags)||!b.metadataTags.length)return json(res,422,{error:'metadata_tags_required'});const record={id:id('consent'),accountId:b.accountId,metadataTags:b.metadataTags,asset:['DISC','VISC','AMDX'].includes(b.asset)?b.asset:'DISC',status:'active',futureUseRevocable:true,createdAt:new Date().toISOString()};db.consents.set(record.id,record);return json(res,201,record)}
 if(req.method==='POST'&&url.pathname==='/api/test-rewards'){const b=await body(req),consent=db.consents.get(b.consentId);if(!consent)return json(res,422,{error:'active_consent_required'});const record={id:id('reward'),accountId:consent.accountId,asset:consent.asset,amount:Number(b.amount||0),mode:'test',transferable:false,consentId:consent.id,createdAt:new Date().toISOString()};db.rewards.set(record.id,record);return json(res,201,record)}
 return json(res,404,{error:'not_found'});
}
function createServer(){restore();return http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');if(url.pathname.startsWith('/api/')&&!allowRequest(req))return json(res,429,{error:'rate_limit_exceeded'});if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(staticFile(req,res))return;json(res,404,{error:'not_found'})}catch(e){json(res,e.message==='invalid_json'?400:500,{error:e.message})}})}
if(require.main===module){const port=Number(process.env.PORT||4173);createServer().listen(port,()=>console.log(`RateMyCustomer running at http://localhost:${port}`))}module.exports={createServer,db,seed,persist,restore,verifyToken,sessionToken,authenticate,rateBuckets};
